Tvc 34 form input
saradvr/fitnessmatch pull request #1
Opened 2021-03-02 22:18 UTC by Otho01

Created a "FormInput" component for future use in all of the forms:

![image](https://user-images.githubusercontent.com/29048009/109722702-0fba6600-7b7b-11eb-8170-21b4a181606f.png)

```
`import React from "react"

class FormInputs extends React.Component {
  render() {
    const {children, type, name, id} = this.props
    return (
      <form>
        <label htmlFor={id}>
          {children}
        </label>
        <input type={type} name={name} id={id}/>
      </form>
    )
  }
}
  
  export default FormInputs;`
```

2021-03-02 22:54 UTC, saradvr commented on src/App.js
> +   <FormInputs type="text" name="email" id="email">Email</FormInputs>
Creo que deberías eliminar el código de prueba de los componentes del App antes del merge.

2021-03-02 22:55 UTC, saradvr approved these changes

2021-03-02 23:32 UTC, SrTeoria approved these changes

2021-03-02 23:43 UTC, Pethofreed approved these changes

2021-03-03 13:02 UTC, simonhoyos requested changes

2021-03-03 13:02 UTC, simonhoyos commented on src/components/FormInputs.js
> +      <form>
No debería haber un elemento form por input. En este caso al hacer submit del formulario solo se enviaría un campo a la vez

2021-03-03 13:02 UTC, simonhoyos commented on src/App.js
> +  {/* <Button type="submit" name="login" id="login">
El código comentado se conoce también como código muerto. Estos hacen que se complique la lectura de código, y la verdad en la mayoría de los casos no se utiliza al final. En términos generales no se recomienda subir código muerto al código final

2021-03-03 13:02 UTC, simonhoyos commented on src/App.js
> +   <FormInputs type="text" name="email" id="email">Email</FormInputs>
Ojo con la identación de los elementos

2021-03-03 15:44 UTC, simonhoyos requested changes

2021-03-03 15:44 UTC, simonhoyos commented on src/App.js
> +   </form>
Ya no es necesario tener este código en App.

2021-03-03 16:31 UTC, Otho01 reviewed
Ya hice los cambios requeridos por Simón

2021-03-03 16:37 UTC, SrTeoria approved these changes

2021-03-03 16:49 UTC, simonhoyos approved these changes

2021-03-03 16:53 UTC, merged