Tvc 2 login
saradvr/fitnessmatch pull request #26
Opened 2021-03-18 01:08 UTC by Otho01

Changed the position of the "Invalid username and password" message in the screen and changed its font-family as well as color.

![image](https://user-images.githubusercontent.com/29048009/111558305-8602bf00-875c-11eb-9d4d-4ee550f5b7e8.png)

2021-03-18 01:26 UTC, saradvr submitted a review, later dismissed

2021-03-18 12:30 UTC, simonhoyos commented
Ojo el PR está apuntando a main

2021-03-18 15:22 UTC, simonhoyos approved these changes, later dismissed

2021-03-18 15:22 UTC, simonhoyos commented on .vscode/settings.json
> +{
Eestas configuraciones al fin las van a dejar compartidas o las van a ignorar

2021-03-19 15:56 UTC, simonhoyos approved these changes

2021-03-19 17:43 UTC, saradvr approved these changes, later dismissed

2021-03-19 17:43 UTC, saradvr commented on .vscode/settings.json
> +  "workbench.colorCustomizations": {
De nuevo te está subiendo el archivo de .vscode, porfa elimínalo y agrégalo a .gitignore para que no lo suba de nuevo. @Otho01

2021-03-19 18:16 UTC, SrTeoria submitted a review, later dismissed

2021-03-19 18:49 UTC, simonhoyos requested changes

2021-03-19 18:49 UTC, simonhoyos commented on .env
> +REACT_APP_SERVER_URL=http://localhost:8000
Puedes remover este archivo y queda listo y agrégalo al gitignore

2021-03-19 20:19 UTC, Otho01 commented on .vscode/settings.json
> +  "workbench.colorCustomizations": {
Ya está agregado a .gitignore

2021-03-19 20:20 UTC, Otho01 commented on .env
> +REACT_APP_SERVER_URL=http://localhost:8000
Ya lo eliminé y agregué al .gitignore

2021-03-19 20:28 UTC, saradvr approved these changes

2021-03-19 21:32 UTC, simonhoyos approved these changes

2021-03-19 21:40 UTC, merged