Tvc 38
saradvr/fitnessmatch pull request #6
Opened 2021-03-04 23:06 UTC by Pethofreed

# Filtros para buscar coach, especialidades, disciplinas y rangos de precio

El filtro de rango de precios será modificado más adelante cuando se trabaje en la US con el estado de la pagina

![filters](https://user-images.githubusercontent.com/72000838/110042496-dbc67880-7d13-11eb-9ccb-682b08978d1f.gif)

2021-03-04 23:10 UTC, saradvr approved these changes, later dismissed

2021-03-04 23:11 UTC, simonhoyos commented
Un comentario un poco más del lado de UX. Los rangos de precios no debería poder seleccionar solo uno a la vez?

2021-03-04 23:17 UTC, simonhoyos requested changes
El código en general está muy bien, la lógica está limpia, bien identado y muy organizado. Solo un par de comentarios y quedamos listos

2021-03-04 23:17 UTC, simonhoyos commented on src/components/Checkbox.js
> +function Checkbox ({nameFor, nameId, nameValue, name, children}) {
Sí nameId y nameFor siempre deberían ser iguales, lo
Mejor sería tener ambos props como uno solo. Incluso al tener un solo valor prevenimos errores por parte de otros desarrolladores que pasen 2 valores diferentes y no les funcione el label

2021-03-04 23:17 UTC, simonhoyos commented on src/components/Filter.js
> +              nameFor = {item.toLowerCase().replace(/ /g, "")}
Lo mismo que el comentario anterior por lo menos para nameId y nameFor. Podríamos analizar si nameValue también lo incluimos ahí.

2021-03-04 23:17 UTC, simonhoyos commented on src/components/FilterContainer.js
> +      <label htmlFor="rango_tres">51.000 - 75.000</label>
Acá también podrías usar el componente Checkbox.

2021-03-04 23:36 UTC, saradvr approved these changes

2021-03-04 23:39 UTC, Pethofreed commented on src/components/Checkbox.js
> +function Checkbox ({nameFor, nameId, nameValue, name, children}) {
> Sí nameId y nameFor siempre deberían ser iguales, lo
> Mejor sería tener ambos props como uno solo. Incluso al tener un solo valor prevenimos errores por parte de otros desarrolladores que pasen 2 valores diferentes y no les funcione el label

ya se actualizó, se dejó un solo prop para htmlFor, id, y también se modificó el value, también se cambiaron los inputs checkbox de rango de precios y se dejaron como dos input text para que el usuario ingrese sus propios rangos.

2021-03-05 01:12 UTC, simonhoyos approved these changes

2021-03-05 17:29 UTC, merged