Create sign up
saradvr/fitnessmatch pull request #7
Opened 2021-03-05 22:37 UTC by SrTeoria

Se creo el Sign up
![gif sign up](https://user-images.githubusercontent.com/71355960/110181272-6c1ac100-7dd9-11eb-81c7-ffc6a95a9a0c.gif)

2021-03-07 02:21 UTC, simonhoyos requested changes

2021-03-07 02:21 UTC, simonhoyos commented on src/components/SignUpForm.js
> +    // console.log(value)
Puedes borrar los comentarios y los console logs

2021-03-08 13:06 UTC, simonhoyos approved these changes

2021-03-08 15:32 UTC, saradvr approved these changes

2021-03-08 15:38 UTC, merged