actualizacion estado de los filtros
saradvr/fitnessmatch pull request #8
Opened 2021-03-08 23:12 UTC by saradvr

# Actualización estado de los filtros

Se agregó el estado de los filtros (checkbox e input text).

![EstadoDeFiltros](https://user-images.githubusercontent.com/75816184/110394037-bb5f2c80-8039-11eb-93ba-72cd57e5db1e.gif)

2021-03-08 23:42 UTC, saradvr commented
# Aplicación filtro de rango de precios

Se agregó el funcionamiento del filtro de rango de precios que actualiza el listado de coaches según ingrese el valor.

![filtroPrecio](https://user-images.githubusercontent.com/75816184/110396373-ef3c5100-803d-11eb-90aa-6a378d55eed9.gif)

2021-03-09 00:30 UTC, saradvr commented
# Aplicación filtros objetivos y disciplinas (checkbox)

![filtrosCheckbox](https://user-images.githubusercontent.com/75816184/110399851-90c6a100-8044-11eb-86d9-8121f1cdd503.gif)

2021-03-09 13:00 UTC, simonhoyos requested changes

2021-03-09 13:00 UTC, simonhoyos commented on src/components/Filter.js
> +        // item = 'Bajar de peso'
Puedes borrar estos comentarios

2021-03-09 13:00 UTC, simonhoyos commented on src/components/CoachCard/styles.js
> +
Sí no le vamos a agregar estilos a un componente es mejor no crear un styled component y utilizar el elemento de HTML directamente en el JSX

2021-03-09 13:00 UTC, simonhoyos commented on src/components/loginForm.js
> +// import {dataCoaches} from "../dataCoaches"
borrar comentarios

2021-03-09 19:02 UTC, simonhoyos approved these changes

2021-03-09 21:23 UTC, Otho01 approved these changes

2021-03-09 21:27 UTC, merged